### ISSUE TITLE
is it possible to do the same for the russian layout?

### ISSUE THREAD

**Issue by glebpigulevsky** [auseika/macos-by-keyboard#2]
/ is not actual anymore

**Comment by auseika** [comment]
Hi, this is technically possible, but not sure if it's a good idea to add that option to the main bundle.
However, since it's a quick thing to implement, maybe I can add a separate bundle to the to the repo or add building instructions, since already seen them requested.

**Comment by wtsiamruk** [comment]
Maybe add missing Russian letters into part when option is pressed? Like и or щ.

**Comment by glebpigulevsky** [comment]
@auseika just create separate branch

**Comment by auseika** [comment]
Will do in a few days.
